package com.healthlink.analytics;

public enum AnalyticsEventType {
    USER_REGISTERED,
    USER_LOGIN,
    MEDICAL_RECORD_VIEW,
    MEDICAL_RECORD_CREATED,
    MEDICAL_RECORD_UPDATED,
    PRESCRIPTION_CREATED,
    PRESCRIPTION_SIGNED,
    PRESCRIPTION_ACKNOWLEDGED,
    LAB_ORDER_CREATED,
    EXPORT_COMPLETED,
    EXPORT_FAILED,
    PHI_ACCESS, // generic PHI access (from aspect)
    NOTIFICATION_ACK,
    WEBHOOK_PUBLISHED
}
